# Generated by Django 5.1.1 on 2024-09-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Base_App", "0002_rename_itemt_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="Image",
            field=models.ImageField(blank=True, upload_to="Item/"),
        ),
    ]
